INSERT INTO gold.signal_activations (
    signal_instance_id,
    signal_id,
    signal_id_version,
    signal_prefix,
    signal_entity,
    signal_family,
    signal_subfamily,
    signal_name,
    signal_tags,
    match_id,
    match_date,
    match_kickoff_utc,
    match_round,
    coverage_level,
    country_code,
    league_id,
    league_name,
    league_round_name,
    parent_league_id,
    parent_league_name,
    parent_league_season,
    parent_league_tournament_id,
    match_started,
    match_finished,
    full_score,
    match_activation_instance_id,
    activated_signal_instance_ids,
    activated_signal_ids,
    activated_signal_entities,
    activated_signal_tags,
    activated_signal_names,
    total_signal_rows,
    unique_signal_count,
    home_team_id,
    home_team_name,
    away_team_id,
    away_team_name,
    home_score,
    away_score,
    stadium_name,
    stadium_city,
    stadium_country,
    stadium_latitude,
    stadium_longitude,
    stadium_capacity,
    stadium_surface,
    attendance,
    referee_name,
    referee_country,
    triggered_side,
    triggered_team_id,
    triggered_team_name,
    triggered_player_id,
    triggered_player_name,
    opponent_team_id,
    opponent_team_name,
    source_table,
    source_row_json,
    source_row_columns,
    inserted_at
)
WITH match_summary AS (
    SELECT
        match_id,
        match_date,
        lower(hex(SHA256(concat('v1', '|', toString(match_id)))))
            AS match_activation_instance_id,
        arraySort(groupUniqArray(signal_instance_id)) AS activated_signal_instance_ids,
        arraySort(groupUniqArray(signal_id)) AS activated_signal_ids,
        arraySort(groupUniqArray(signal_entity)) AS activated_signal_entities,
        arraySort(arrayDistinct(arrayFlatten(groupArray(signal_tags)))) AS activated_signal_tags,
        arraySort(groupUniqArray(signal_name)) AS activated_signal_names,
        toUInt32(count()) AS total_signal_rows,
        toUInt16(length(groupUniqArray(signal_id))) AS unique_signal_count
    FROM gold.signal_activations_stage
    GROUP BY match_id, match_date
)
SELECT
    stage.signal_instance_id,
    stage.signal_id,
    stage.signal_id_version,
    stage.signal_prefix,
    stage.signal_entity,
    stage.signal_family,
    stage.signal_subfamily,
    stage.signal_name,
    stage.signal_tags,
    stage.match_id,
    stage.match_date,
    stage.match_kickoff_utc,
    stage.match_round,
    stage.coverage_level,
    stage.country_code,
    stage.league_id,
    stage.league_name,
    stage.league_round_name,
    stage.parent_league_id,
    stage.parent_league_name,
    stage.parent_league_season,
    stage.parent_league_tournament_id,
    stage.match_started,
    stage.match_finished,
    stage.full_score,
    match_summary.match_activation_instance_id,
    match_summary.activated_signal_instance_ids,
    match_summary.activated_signal_ids,
    match_summary.activated_signal_entities,
    match_summary.activated_signal_tags,
    match_summary.activated_signal_names,
    match_summary.total_signal_rows,
    match_summary.unique_signal_count,
    stage.home_team_id,
    stage.home_team_name,
    stage.away_team_id,
    stage.away_team_name,
    stage.home_score,
    stage.away_score,
    stage.stadium_name,
    stage.stadium_city,
    stage.stadium_country,
    stage.stadium_latitude,
    stage.stadium_longitude,
    stage.stadium_capacity,
    stage.stadium_surface,
    stage.attendance,
    stage.referee_name,
    stage.referee_country,
    stage.triggered_side,
    stage.triggered_team_id,
    stage.triggered_team_name,
    stage.triggered_player_id,
    stage.triggered_player_name,
    stage.opponent_team_id,
    stage.opponent_team_name,
    stage.source_table,
    stage.source_row_json,
    stage.source_row_columns,
    stage.inserted_at
FROM gold.signal_activations_stage AS stage
INNER JOIN match_summary
    ON match_summary.match_id = stage.match_id
   AND match_summary.match_date = stage.match_date;
