-- Signal tables for entity=match, family=creativity, subfamily=playmaking

CREATE TABLE IF NOT EXISTS gold.sig_match_creativity_playmaking_the_creativity_clash (
    match_id Int32,
    match_date Date,
    home_team_id Nullable(Int32),
    home_team_name Nullable(String),
    away_team_id Nullable(Int32),
    away_team_name Nullable(String),
    home_score Nullable(Int32),
    away_score Nullable(Int32),
    triggered_side LowCardinality(String),
    triggered_team_id Nullable(Int32),
    triggered_team_name Nullable(String),
    opponent_team_id Nullable(Int32),
    opponent_team_name Nullable(String),
    trigger_threshold_min_team_expected_assists Float32,
    match_total_expected_assists Float32,
    triggered_team_expected_assists Float32,
    opponent_expected_assists Float32,
    expected_assists_delta Float32,
    triggered_team_key_passes Int32,
    opponent_key_passes Int32,
    key_pass_delta Int32,
    triggered_team_expected_assists_per_key_pass Float32,
    opponent_expected_assists_per_key_pass Float32,
    expected_assists_per_key_pass_delta Float32,
    triggered_team_goals Int32,
    opponent_goals Int32,
    goal_delta Int32,
    triggered_team_chance_conversion_pct Float32,
    opponent_chance_conversion_pct Float32,
    chance_conversion_delta_pct Float32,
    triggered_team_total_shots Int32,
    opponent_total_shots Int32,
    total_shots_delta Int32,
    triggered_team_shots_on_target Int32,
    opponent_shots_on_target Int32,
    shots_on_target_delta Int32,
    triggered_team_expected_goals Float32,
    opponent_expected_goals Float32,
    expected_goals_delta Float32,
    triggered_team_big_chances Int32,
    opponent_big_chances Int32,
    big_chances_delta Int32,
    triggered_team_pass_attempts Int32,
    opponent_pass_attempts Int32,
    triggered_team_pass_accuracy_pct Float32,
    opponent_pass_accuracy_pct Float32,
    pass_accuracy_delta_pct Float32,
    triggered_team_possession_pct Float32,
    opponent_possession_pct Float32,
    possession_delta_pct Float32,
    triggered_team_opposition_half_passes Int32,
    opponent_opposition_half_passes Int32,
    opposition_half_passes_delta Int32,
    triggered_team_touches_opposition_box Int32,
    opponent_touches_opposition_box Int32,
    opposition_box_touches_delta Int32,
    inserted_at DateTime DEFAULT now()
) ENGINE = ReplacingMergeTree(inserted_at)
ORDER BY (match_id, triggered_side)
PARTITION BY toYYYYMM(match_date);
